Repository openimsdk/open-im-sdk-core-Indexdb-doc, pull requests merged in 2024-07, with the labels that each got.

#5 docs: update docs to v3.8 feature.
  black.md
  chat_logs_conversationID.md
  local_app_sdk_version.md
  local_black.md
  local_conversation.md
  local_friend.md
  local_group.md
  local_group_member.md
  local_group_request.md
  local_notification.md
  local_version_sync.md
Labels: size/XL

#6 fix: remove uncorrect contents.
  local_group_member.md
Labels: size/XS

#10 feat:group display is read
  local_group.md
Labels: size/S

#8 fix: update docs contents
  chat_logs_conversationID.md
  local_group.md
  local_group_member.md
  local_notification.md
  local_super_group_chat_log.md
Labels: size/M

#11 docs: update sdk-core new method docs
  local_conversation.md
  local_table_master.md
Labels: size/M

#12 fix: update uncorrect table name.
  local_conversation.md
Labels: size/XS

#14 update initChatlog call functions.
  chat_logs_conversationID.md
Labels: size/XS
